### ISSUE TITLE
MATE-20_EMUI_11.0.0主要是反编译哪些文件呢

### ISSUE THREAD

**Issue by cooperise** [dstmath/HWFramework#6]
MATE-20_EMUI_11.0.0主要是反编译哪些文件呢？我这边编译好像老是会少一些文件

**Comment by cooperise** [comment]
能否简单阐释一下Mac上EMUI Android 10反编译的步骤呢

**Comment by dstmath** [comment]
find . -name "*.oat" -o -name "*.odex" -o -name "*.vdex" -o -name "*.jar"

**Comment by dstmath** [comment]
@cooperise 
find . -name "*.oat" -o -name "*.odex" -o -name "*.vdex" -o -name "*.jar"
